name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Nodemon Globally
        run: npm install -g nodemon

      - name: Run Server
        run: npm start &

      - name: Run API Tests
        run: ./test_api_commands.sh
